name: CD

# Controls when the workflow will run
on:
  push:
    branches:
      - develop
     
  workflow_dispatch:  # Allows manual triggering

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: "us-east-1"  # replace with your region if different

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -backend-config=environments/dev/backend.tf

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -var-file=environments/dev/dev.tfvars

      # Uncomment the following lines if you want to automatically apply the plan
      # - name: Terraform Apply
      #   run: terraform apply -no-color -auto-approve -var-file=environments/dev/dev.tfvars

      - name: Terraform Destroy
        run: terraform destroy -no-color -auto-approve -var-file=environments/dev/dev.tfvars
